#include <AiPlugin/AiPluginPCH.h>



PL_STATICLINK_LIBRARY(AiPlugin)
{
  if (bReturn)
    return;
}

PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Components_EqsQueryComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Components_EqsQueryTestComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Implementation_EqsContext);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Implementation_EqsExecution);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Implementation_EqsGenerator);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Implementation_EqsQueryResource);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Implementation_EqsStartup);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Implementation_EqsTest);
PL_STATICLINK_REFERENCE(AiPlugin_Eqs_Implementation_EqsWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_AiDestructionResponseComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_CrowdAgentComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_NavBlockerComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_NavLinkComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Implementation_CrowdWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_NavMeshObstacleComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_NavMeshPathTestComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_NavMeshPrebuildComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_NavigationComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Components_VoxelNavigationComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Implementation_NavMeshWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Implementation_VoxelNavigation);
PL_STATICLINK_REFERENCE(AiPlugin_Navigation_Implementation_VoxelWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Components_CoverPointComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Components_SmartObjectComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Components_TacticalQueryTestComponent);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Implementation_CoverGeneration);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Implementation_SmartObjects);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Implementation_TacticalQuery);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Implementation_SquadWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_Tactical_Implementation_TacticalWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Components_AiAgentComponent);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Components_AiLodCenterComponent);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiArchetypeResource);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiBehaviorLogic);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiBehaviorResource);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiBrainWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiDecisionStartup);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiEqsStates);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiInput);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiScoring);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiSmartObjectStates);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiStateMachineStates);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiTacticalStates);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Decision_AiUtilityEvaluator);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Perception_AiPerception);
PL_STATICLINK_REFERENCE(AiPlugin_UtilityAI_Perception_AiPerceptionWorldModule);
PL_STATICLINK_REFERENCE(AiPlugin_Utils_AiCVars);
